[package]
name = "le-presentation"
version = "0.1.0"
edition = "2021"

[features]
embedded-device = []

[dependencies]
axum = { version = "0.8", features = ["ws"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tower-http = { version = "0.6", features = ["cors", "fs"] }
ordermap = "1.1.0"
notify = "8.0"
sysinfo = "0.32"
zip = "2.2"
roxmltree = "0.20"
